# Generated by Django 3.2.9 on 2021-11-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centerhead', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('admitted', 'admitted'), ('not-interested', 'not-interested'), ('followup', 'followup')], default='followup', max_length=30)),
                ('followup_date', models.DateField()),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerhead.course')),
            ],
        ),
    ]
