# Generated by Django 3.2.9 on 2021-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerhead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=120)),
            ],
        ),
    ]
